# Generated by Django 5.2.2 on 2025-06-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('original_price', models.FloatField()),
                ('image', models.URLField()),
                ('rating', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
